# -----------------------------------------------------------------------------
# MULTIMODAL-IA--TFG - Proyecto TFG
# (c) 2025 Pablo González García
# Universidad de Oviedo, Escuela Politécncia de Ingeniería de Gijón
# Archivo: config/settings.yaml
# Autor: Pablo González García
# Descripción:
# Archivo de configuración principal del asistente inteligente.
# Contiene parámetros relacionados con el sistema de logging,
# la conexión a bases de datos, y otros ajustes generales del sistema.
# -----------------------------------------------------------------------------

# ---- Parámetros ---- #
logger:
  level: INFO             # Nivel de log: DEBIG, INFO, WARNING, ERROR, CRITICAL
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'    # Formato del mensaje del log.
  datefmt: '%d-%m-%Y %H:%M:%S'    # Formato de la fecha.
  path: 'logs'            # Ruta al directorio de logs.
  max_bytes: 10485760     # 10 MB.
  backup_count: 5         # Número de archivos de log de respaldo.

ollama:
  host: '127.0.0.1'             # Host del servicio ollama.
  port: 11434                   # Puerto del servicio ollama.
  bin: 'bin/ollama/ollama'      # Nombre del binario.
  silent: False                 # Si se debe mostrar los mensajes del propio servicio de ollama.
  file: 'logs/ollama_serve.log'      # Ruta al directorio de logs.
  model: 'llama3.2:1b'             # Nombre del modelo a utilizar.
  chat_history_max_size: 10     # Tamaño máximo del historial de chat.